### ISSUE TITLE
this.name.padStart is not a function

### ISSUE THREAD

**Issue by kazarmy** [radare/radare2-regressions#1008]
Seeing the following error:

```
this.name.padStart is not a function
TypeError: this.name.padStart is not a function
    at NewRegressions.printReport (/home/travis/build/radare/radare2/radare2-regressions/new/index.js:473:62)
    at Promise.all.then.res (/home/travis/build/radare/radare2/radare2-regressions/new/index.js:368:14)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

on Travis (i.e. https://travis-ci.org/radare/radare2/jobs/274975426). According to this [Node.js support matrix](http://node.green/#ES2017-features-String-padding), the error indicates that the Node.js version on Travis should be upgraded. I've tried `r2r.js` with Node.js 8.4.0 and the error no longer appears.

**Comment by radare** [comment]
ah right padStart comes with node8, which will be LTS this month. we can add a padStart helper to solve that
