### ISSUE TITLE
NodeJS fails on both Travis and AppVeyor.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-regressions#1287]
AppVeyor:
```
Install-Product node $env:nodejs_version
Uninstalling node 4.8.7 (x86)...
Installing node 10.0.0 (x86)...
node --version
v10.0.0
node bin/r2r.js
internal/util.js:260
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type string
    at promisify (internal/util.js:260:11)
    at Object.<anonymous> (C:\projects\radare2-shvdd\radare2-regressions\new\index.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\projects\radare2-shvdd\radare2-regressions\new\bin\r2r.js:3:24)
Command exited with code 1
```

Travis:
```
cd new && node bin/r2r.js
/home/travis/build/radare/radare2/radare2-regressions/new/index.js:5
const fs = promisify('fs');
           ^
TypeError: promisify is not a function
    at Object.<anonymous> (/home/travis/build/radare/radare2/radare2-regressions/new/index.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/radare/radare2/radare2-regressions/new/bin/r2r.js:3:24)
    at Module._compile (module.js:571:32)
make[1]: *** [js-tests] Error 1
```

**Comment by radare** [comment]
fixed
