### ISSUE TITLE
Cannot use the $dec alias

### ISSUE THREAD

**Issue by gu10ng1t** [radare/radare2-regressions#1318]
I'v compiled the retdec and successfully ran it outside radare2, but when I try to use $dec alias it fails:

```
/home/vagrant/.local/share/radare2/r2pm/git/r2retdec/node_modules/r2pipe/index.js:403
    const ls = proc.spawn(this.r2bin, ['-qc.:' + port].concat(...opts).concat(file));
                                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vagrant/.local/share/radare2/r2pm/git/r2retdec/r2retdec.js:1:78)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```
I known that the problem is that unexpected token **...**, but anyway, I'll show below my configurations.

**The alias you can see below**:
```
vagrant@ubuntu-xenial:/vagrant/test$ cat ~/.radare2rc 
$dec=#!pipe node /home/vagrant/.local/share/radare2/r2pm/git//r2retdec/r2retdec.js
```
**The link I provided to retdec works as expected**:
```
vagrant@ubuntu-xenial:/vagrant/test$ file ~/.r2retdec 
/home/vagrant/.r2retdec: symbolic link to /opt/retdec/bin/retdec-decompiler.sh
```
**radare2 version**:
```
vagrant@ubuntu-xenial:/vagrant/test$ r2 -v
radare2 2.6.0-git 18219 @ linux-x86-64 git.2.5.0-297-gefda76c
commit: efda76cc18f164dce2e468bbe095b6f0c6e5a43a build: 2018-05-20__01:20:18
```
**asciinema showing a simple test**:
[![asciicast](https://asciinema.org/a/182526.png)](https://asciinema.org/a/182526)

So, how I'm supposed to use the retdec inside radare2? Sorry, I didn't find any documentation explaining it.

**Comment by radare** [comment]
not related to this repo
