### ISSUE TITLE
Some JS error on AppVeyor

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-regressions#1386]
```
C:\projects\radare2-shvdd\radare2-regressions\new\index.js:418
            while (!lines[i].startsWith(endString)) {
                             ^
TypeError: Cannot read property 'startsWith' of undefined
    at NewRegressions.runTests (C:\projects\radare2-shvdd\radare2-regressions\new\index.js:418:30)
    at Gunzip.zlib.gunzip [as cb] (C:\projects\radare2-shvdd\radare2-regressions\new\index.js:495:14)
    at Gunzip.zlibBufferOnError (zlib.js:102:8)
    at Gunzip.emit (events.js:182:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:156:8)
Command exited with code 1
```

**Comment by radare** [comment]
Pls update node. This startsWith thing was introduced in js in 2012

**Comment by radare** [comment]
Oh wait its undefined ill add a fix now 1m

**Comment by kazarmy** [comment]
`lines[i]` shouldn't be undefined at that line unless the test is misstructured.

**Comment by kazarmy** [comment]
the last test -> a test

**Comment by radare** [comment]
Theres no reason to have an undefined there and that loops is wrong from the roots. But i just did a quickfix
